version: '3'

vars:
  VDRIVE: /Volumes/FS PRO
  LAYOUT: layout1.txt
  SETTINGS: kbd_settings.txt

tasks:
  default:
    deps: [layout, settings]
    
  layout:
    deps: [vdrive-mounted]
    cmds:
      - cp "layouts/{{.LAYOUT}}" "{{.VDRIVE}}/layouts"
    sources:
      - layouts/{{.LAYOUT}}

  settings:
    deps: [vdrive-mounted]
    cmds:
      - cp "settings/{{.SETTINGS}}" "{{.VDRIVE}}/settings"
    sources:
      - settings/{{.SETTINGS}}

  vdrive-mounted:
    preconditions:
      - sh: test -d "{{.VDRIVE}}"
        msg: Mount the v-Drive with SmartSet+F8
