version: '3'

vars:
  VDRIVE: /Volumes/FS PRO
  SETTINGS: kbd_settings.txt

tasks:
  default:
    deps: [layout, settings]

  unmount:
    deps: [vdrive-mounted]
    cmds:
      - diskutil unmount "{{.VDRIVE}}"
      - cmd: echo "Disconnect the v-Drive with SmartSet+F8"
        silent: true
    
  layout:
    deps: [vdrive-mounted]
    cmds:
      - cp layouts/layout*.txt "{{.VDRIVE}}/layouts"
      - task: howto-refresh
    sources:
      - layouts/layout*.txt

  settings:
    deps: [vdrive-mounted]
    cmds:
      - cp "settings/{{.SETTINGS}}" "{{.VDRIVE}}/settings"
      - task: howto-refresh
    sources:
      - settings/{{.SETTINGS}}

  howto-refresh:
    run: once
    cmds:
      - cmd: echo "Refresh with SmartSet+Layout"
        silent: true

  vdrive-mounted:
    preconditions:
      - sh: test -d "{{.VDRIVE}}"
        msg: Mount the v-Drive with SmartSet+F8
